# Generated by Django 4.0.3 on 2022-03-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
